module C2PA
  module Actions
    CREATED         = "c2pa.created"
    OPENED          = "c2pa.opened"
    EDITED          = "c2pa.edited"
    EDITED_METADATA = "c2pa.edited.metadata"
    ADJUSTED_COLOR  = "c2pa.adjustedColor"
    CHANGED_SPEED   = "c2pa.changedSpeed"
    CONVERTED       = "c2pa.converted"
    CROPPED         = "c2pa.cropped"
    DELETED         = "c2pa.deleted"
    DRAWING         = "c2pa.drawing"
    DUBBED          = "c2pa.dubbed"
    ENHANCED        = "c2pa.enhanced"
    FILTERED        = "c2pa.filtered"
    ORIENTATION     = "c2pa.orientation"
    PLACED          = "c2pa.placed"
    PUBLISHED       = "c2pa.published"
    REDACTED        = "c2pa.redacted"
    REMOVED         = "c2pa.removed"
    REPACKAGED      = "c2pa.repackaged"
    RESIZED         = "c2pa.resized"
    TRANSLATED      = "c2pa.translated"
    TRANSCODED      = "c2pa.transcoded"
    TRIMMED         = "c2pa.trimmed"
    UNKNOWN         = "c2pa.unknown"
    WATERMARKED     = "c2pa.watermarked"
  end
end
